[package]
name = "xtask"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0.97"
argh = "0.1.13"
cargo_metadata = "0.19.2"
ctrlc = "3.4.5"
walkdir = "2.5.0"
xtask-util = { path = "../lib/xtask-util-rs" }
